language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - libcunit1
            - libcunit1-dev
            - libcurl3
            - libcurl3-nss-dev
      env: CMAKE_BUILD_TYPE=DEBUG BUILD_TESTS=ON

    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - libcunit1
            - libcunit1-dev
            - libcurl3
            - libcurl3-nss-dev
      env: CMAKE_BUILD_TYPE=RELEASE BUILD_TESTS=ON

script:
  - cmake --version
  - make --version
  - ls
  - echo $CMAKE_BUILD_TYPE $BUILD_TESTS
