language: c

matrix:
  include:
    - os: linux
      jdk: openjdk8
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - dart
            - libcunit1
            - libcunit1-dev
            - libcurl3
            - libcurl3-nss-dev
      env: CMAKE_BUILD_TYPE=DEBUG BUILD_TESTS=ON

before_script:
  - sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_unstable.list > /etc/apt/sources.list.d/dart_unstable.list'
  - sudo apt-get update
  - sudo apt-get install dart

script:
  - cmake --version
  - make --version
  - java --version
  - dart --version
  - ls
  - echo $CMAKE_BUILD_TYPE $BUILD_TESTS
