language: android
jdk: openjdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-21

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - ninja-build
          sources:
            - ubuntu-toolchain-r-test
      env: CMAKE_BUILD_TYPE=DEBUG

    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - ninja-build
          sources:
            - ubuntu-toolchain-r-test
      env: CMAKE_BUILD_TYPE=RELEASE

script:
  - ./gradlew connectedAndroidTest
